### ISSUE TITLE
Code cleanup and organization

### ISSUE THREAD

**Issue by slovit** [slovit/simple-bank#2]
Organize
Move classes into different packages for easier navigation.
Base package is `com.alexslo.bank`
High level java packages overview:
```
.
|_controller   // location for servlets
|_core         // core classes. E.g. configuration, project wide constants
|_dao          // persistence related classes
|_model
|_service
   |_impl
Application.java // application entry point. Contains the `main()` method
```
## Remove unnecessary classes

What the purpose of
```
ContextListener
```

**Comment by AlexSlob** [comment]
Before starting I have organizational questions.
There's no need for me to download this repository on my PC? I can continue working with my old repo, commit to it and it will be also changed in your repo, because it's forked?
Or I have to work it this currents repo?

**Comment by slovit** [comment]
You have to use this repository. Changes to `AlexSlob/PaymentsWebProject` repository are not reflected here.
